// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs).
// git: 1de4f0c (Fri Jan 24 11:10:52 2025 +0100)
// Compiled with GHC 9.4.8.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_f32_1d;
struct futhark_f32_1d *futhark_new_f32_1d(struct futhark_context *ctx, const float *data, int64_t dim0);
struct futhark_f32_1d *futhark_new_raw_f32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
int futhark_values_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr, float *data);
int futhark_index_f32_1d(struct futhark_context *ctx, float *out, struct futhark_f32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
const int64_t *futhark_shape_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
struct futhark_f64_1d;
struct futhark_f64_1d *futhark_new_f64_1d(struct futhark_context *ctx, const double *data, int64_t dim0);
struct futhark_f64_1d *futhark_new_raw_f64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
int futhark_values_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr, double *data);
int futhark_index_f64_1d(struct futhark_context *ctx, double *out, struct futhark_f64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
const int64_t *futhark_shape_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
struct futhark_i16_1d;
struct futhark_i16_1d *futhark_new_i16_1d(struct futhark_context *ctx, const int16_t *data, int64_t dim0);
struct futhark_i16_1d *futhark_new_raw_i16_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr);
int futhark_values_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr, int16_t *data);
int futhark_index_i16_1d(struct futhark_context *ctx, int16_t *out, struct futhark_i16_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr);
const int64_t *futhark_shape_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr);
struct futhark_i32_1d;
struct futhark_i32_1d *futhark_new_i32_1d(struct futhark_context *ctx, const int32_t *data, int64_t dim0);
struct futhark_i32_1d *futhark_new_raw_i32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
int futhark_values_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr, int32_t *data);
int futhark_index_i32_1d(struct futhark_context *ctx, int32_t *out, struct futhark_i32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
const int64_t *futhark_shape_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
struct futhark_i64_1d;
struct futhark_i64_1d *futhark_new_i64_1d(struct futhark_context *ctx, const int64_t *data, int64_t dim0);
struct futhark_i64_1d *futhark_new_raw_i64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
int futhark_values_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr, int64_t *data);
int futhark_index_i64_1d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
const int64_t *futhark_shape_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
struct futhark_u8_2d;
struct futhark_u8_2d *futhark_new_u8_2d(struct futhark_context *ctx, const uint8_t *data, int64_t dim0, int64_t dim1);
struct futhark_u8_2d *futhark_new_raw_u8_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_u8_2d(struct futhark_context *ctx, struct futhark_u8_2d *arr);
int futhark_values_u8_2d(struct futhark_context *ctx, struct futhark_u8_2d *arr, uint8_t *data);
int futhark_index_u8_2d(struct futhark_context *ctx, uint8_t *out, struct futhark_u8_2d *arr, int64_t i0, int64_t i1);
unsigned char *futhark_values_raw_u8_2d(struct futhark_context *ctx, struct futhark_u8_2d *arr);
const int64_t *futhark_shape_u8_2d(struct futhark_context *ctx, struct futhark_u8_2d *arr);

// Opaque values
struct futhark_opaque_sortInfo_double;
struct futhark_opaque_sortInfo_float;
struct futhark_opaque_sortInfo_int;
struct futhark_opaque_sortInfo_long;
struct futhark_opaque_sortInfo_short;
struct futhark_opaque_sortStruct_double;
struct futhark_opaque_sortStruct_float;
struct futhark_opaque_sortStruct_int;
struct futhark_opaque_sortStruct_long;
struct futhark_opaque_sortStruct_short;
int futhark_free_opaque_sortInfo_double(struct futhark_context *ctx, struct futhark_opaque_sortInfo_double *obj);
int futhark_store_opaque_sortInfo_double(struct futhark_context *ctx, const struct futhark_opaque_sortInfo_double *obj, void **p, size_t *n);
struct futhark_opaque_sortInfo_double *futhark_restore_opaque_sortInfo_double(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortInfo_double_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_double *obj);
int futhark_project_opaque_sortInfo_double_xs(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_sortInfo_double *obj);
int futhark_new_opaque_sortInfo_double(struct futhark_context *ctx, struct futhark_opaque_sortInfo_double **out, const struct futhark_i64_1d *f_is, const struct futhark_f64_1d *f_xs);
int futhark_free_opaque_sortInfo_float(struct futhark_context *ctx, struct futhark_opaque_sortInfo_float *obj);
int futhark_store_opaque_sortInfo_float(struct futhark_context *ctx, const struct futhark_opaque_sortInfo_float *obj, void **p, size_t *n);
struct futhark_opaque_sortInfo_float *futhark_restore_opaque_sortInfo_float(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortInfo_float_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_float *obj);
int futhark_project_opaque_sortInfo_float_xs(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_sortInfo_float *obj);
int futhark_new_opaque_sortInfo_float(struct futhark_context *ctx, struct futhark_opaque_sortInfo_float **out, const struct futhark_i64_1d *f_is, const struct futhark_f32_1d *f_xs);
int futhark_free_opaque_sortInfo_int(struct futhark_context *ctx, struct futhark_opaque_sortInfo_int *obj);
int futhark_store_opaque_sortInfo_int(struct futhark_context *ctx, const struct futhark_opaque_sortInfo_int *obj, void **p, size_t *n);
struct futhark_opaque_sortInfo_int *futhark_restore_opaque_sortInfo_int(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortInfo_int_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_int *obj);
int futhark_project_opaque_sortInfo_int_xs(struct futhark_context *ctx, struct futhark_i32_1d **out, const struct futhark_opaque_sortInfo_int *obj);
int futhark_new_opaque_sortInfo_int(struct futhark_context *ctx, struct futhark_opaque_sortInfo_int **out, const struct futhark_i64_1d *f_is, const struct futhark_i32_1d *f_xs);
int futhark_free_opaque_sortInfo_long(struct futhark_context *ctx, struct futhark_opaque_sortInfo_long *obj);
int futhark_store_opaque_sortInfo_long(struct futhark_context *ctx, const struct futhark_opaque_sortInfo_long *obj, void **p, size_t *n);
struct futhark_opaque_sortInfo_long *futhark_restore_opaque_sortInfo_long(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortInfo_long_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_long *obj);
int futhark_project_opaque_sortInfo_long_xs(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_long *obj);
int futhark_new_opaque_sortInfo_long(struct futhark_context *ctx, struct futhark_opaque_sortInfo_long **out, const struct futhark_i64_1d *f_is, const struct futhark_i64_1d *f_xs);
int futhark_free_opaque_sortInfo_short(struct futhark_context *ctx, struct futhark_opaque_sortInfo_short *obj);
int futhark_store_opaque_sortInfo_short(struct futhark_context *ctx, const struct futhark_opaque_sortInfo_short *obj, void **p, size_t *n);
struct futhark_opaque_sortInfo_short *futhark_restore_opaque_sortInfo_short(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortInfo_short_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_short *obj);
int futhark_project_opaque_sortInfo_short_xs(struct futhark_context *ctx, struct futhark_i16_1d **out, const struct futhark_opaque_sortInfo_short *obj);
int futhark_new_opaque_sortInfo_short(struct futhark_context *ctx, struct futhark_opaque_sortInfo_short **out, const struct futhark_i64_1d *f_is, const struct futhark_i16_1d *f_xs);
int futhark_free_opaque_sortStruct_double(struct futhark_context *ctx, struct futhark_opaque_sortStruct_double *obj);
int futhark_store_opaque_sortStruct_double(struct futhark_context *ctx, const struct futhark_opaque_sortStruct_double *obj, void **p, size_t *n);
struct futhark_opaque_sortStruct_double *futhark_restore_opaque_sortStruct_double(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortStruct_double_k(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_sortStruct_double *obj);
int futhark_project_opaque_sortStruct_double_pL(struct futhark_context *ctx, struct futhark_u8_2d **out, const struct futhark_opaque_sortStruct_double *obj);
int futhark_new_opaque_sortStruct_double(struct futhark_context *ctx, struct futhark_opaque_sortStruct_double **out, const struct futhark_f64_1d *f_k, const struct futhark_u8_2d *f_pL);
int futhark_free_opaque_sortStruct_float(struct futhark_context *ctx, struct futhark_opaque_sortStruct_float *obj);
int futhark_store_opaque_sortStruct_float(struct futhark_context *ctx, const struct futhark_opaque_sortStruct_float *obj, void **p, size_t *n);
struct futhark_opaque_sortStruct_float *futhark_restore_opaque_sortStruct_float(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortStruct_float_k(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_sortStruct_float *obj);
int futhark_project_opaque_sortStruct_float_pL(struct futhark_context *ctx, struct futhark_u8_2d **out, const struct futhark_opaque_sortStruct_float *obj);
int futhark_new_opaque_sortStruct_float(struct futhark_context *ctx, struct futhark_opaque_sortStruct_float **out, const struct futhark_f32_1d *f_k, const struct futhark_u8_2d *f_pL);
int futhark_free_opaque_sortStruct_int(struct futhark_context *ctx, struct futhark_opaque_sortStruct_int *obj);
int futhark_store_opaque_sortStruct_int(struct futhark_context *ctx, const struct futhark_opaque_sortStruct_int *obj, void **p, size_t *n);
struct futhark_opaque_sortStruct_int *futhark_restore_opaque_sortStruct_int(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortStruct_int_k(struct futhark_context *ctx, struct futhark_i32_1d **out, const struct futhark_opaque_sortStruct_int *obj);
int futhark_project_opaque_sortStruct_int_pL(struct futhark_context *ctx, struct futhark_u8_2d **out, const struct futhark_opaque_sortStruct_int *obj);
int futhark_new_opaque_sortStruct_int(struct futhark_context *ctx, struct futhark_opaque_sortStruct_int **out, const struct futhark_i32_1d *f_k, const struct futhark_u8_2d *f_pL);
int futhark_free_opaque_sortStruct_long(struct futhark_context *ctx, struct futhark_opaque_sortStruct_long *obj);
int futhark_store_opaque_sortStruct_long(struct futhark_context *ctx, const struct futhark_opaque_sortStruct_long *obj, void **p, size_t *n);
struct futhark_opaque_sortStruct_long *futhark_restore_opaque_sortStruct_long(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortStruct_long_k(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortStruct_long *obj);
int futhark_project_opaque_sortStruct_long_pL(struct futhark_context *ctx, struct futhark_u8_2d **out, const struct futhark_opaque_sortStruct_long *obj);
int futhark_new_opaque_sortStruct_long(struct futhark_context *ctx, struct futhark_opaque_sortStruct_long **out, const struct futhark_i64_1d *f_k, const struct futhark_u8_2d *f_pL);
int futhark_free_opaque_sortStruct_short(struct futhark_context *ctx, struct futhark_opaque_sortStruct_short *obj);
int futhark_store_opaque_sortStruct_short(struct futhark_context *ctx, const struct futhark_opaque_sortStruct_short *obj, void **p, size_t *n);
struct futhark_opaque_sortStruct_short *futhark_restore_opaque_sortStruct_short(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortStruct_short_k(struct futhark_context *ctx, struct futhark_i16_1d **out, const struct futhark_opaque_sortStruct_short *obj);
int futhark_project_opaque_sortStruct_short_pL(struct futhark_context *ctx, struct futhark_u8_2d **out, const struct futhark_opaque_sortStruct_short *obj);
int futhark_new_opaque_sortStruct_short(struct futhark_context *ctx, struct futhark_opaque_sortStruct_short **out, const struct futhark_i16_1d *f_k, const struct futhark_u8_2d *f_pL);

// Entry points
int futhark_entry_argmin_double(struct futhark_context *ctx, int64_t *out0, const struct futhark_f64_1d *in0);
int futhark_entry_argmin_float(struct futhark_context *ctx, int64_t *out0, const struct futhark_f32_1d *in0);
int futhark_entry_argmin_int(struct futhark_context *ctx, int64_t *out0, const struct futhark_i32_1d *in0);
int futhark_entry_argmin_long(struct futhark_context *ctx, int64_t *out0, const struct futhark_i64_1d *in0);
int futhark_entry_argmin_short(struct futhark_context *ctx, int64_t *out0, const struct futhark_i16_1d *in0);
int futhark_entry_mergeSortColumn_double(struct futhark_context *ctx, struct futhark_opaque_sortInfo_double **out0, const int64_t in0, const struct futhark_f64_1d *in1);
int futhark_entry_mergeSortColumn_float(struct futhark_context *ctx, struct futhark_opaque_sortInfo_float **out0, const int64_t in0, const struct futhark_f32_1d *in1);
int futhark_entry_mergeSortColumn_int(struct futhark_context *ctx, struct futhark_opaque_sortInfo_int **out0, const int64_t in0, const struct futhark_i32_1d *in1);
int futhark_entry_mergeSortColumn_long(struct futhark_context *ctx, struct futhark_opaque_sortInfo_long **out0, const int64_t in0, const struct futhark_i64_1d *in1);
int futhark_entry_mergeSortColumn_short(struct futhark_context *ctx, struct futhark_opaque_sortInfo_short **out0, const int64_t in0, const struct futhark_i16_1d *in1);
int futhark_entry_mergeSortRelation_double(struct futhark_context *ctx, struct futhark_opaque_sortStruct_double **out0, const struct futhark_opaque_sortStruct_double *in0);
int futhark_entry_mergeSortRelation_float(struct futhark_context *ctx, struct futhark_opaque_sortStruct_float **out0, const struct futhark_opaque_sortStruct_float *in0);
int futhark_entry_mergeSortRelation_int(struct futhark_context *ctx, struct futhark_opaque_sortStruct_int **out0, const struct futhark_opaque_sortStruct_int *in0);
int futhark_entry_mergeSortRelation_long(struct futhark_context *ctx, struct futhark_opaque_sortStruct_long **out0, const struct futhark_opaque_sortStruct_long *in0);
int futhark_entry_mergeSortRelation_short(struct futhark_context *ctx, struct futhark_opaque_sortStruct_short **out0, const struct futhark_opaque_sortStruct_short *in0);
int futhark_entry_orderByIndices_double(struct futhark_context *ctx, struct futhark_f64_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_1d *in2, const struct futhark_f64_1d *in3);
int futhark_entry_orderByIndices_float(struct futhark_context *ctx, struct futhark_f32_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_1d *in2, const struct futhark_f32_1d *in3);
int futhark_entry_orderByIndices_int(struct futhark_context *ctx, struct futhark_i32_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_1d *in2, const struct futhark_i32_1d *in3);
int futhark_entry_orderByIndices_long(struct futhark_context *ctx, struct futhark_i64_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_1d *in2, const struct futhark_i64_1d *in3);
int futhark_entry_orderByIndices_short(struct futhark_context *ctx, struct futhark_i16_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_1d *in2, const struct futhark_i16_1d *in3);
int futhark_entry_radixSortColumn_double(struct futhark_context *ctx, struct futhark_opaque_sortInfo_double **out0, const int64_t in0, const int16_t in1, const struct futhark_f64_1d *in2);
int futhark_entry_radixSortColumn_float(struct futhark_context *ctx, struct futhark_opaque_sortInfo_float **out0, const int64_t in0, const int16_t in1, const struct futhark_f32_1d *in2);
int futhark_entry_radixSortColumn_int(struct futhark_context *ctx, struct futhark_opaque_sortInfo_int **out0, const int64_t in0, const int16_t in1, const struct futhark_i32_1d *in2);
int futhark_entry_radixSortColumn_long(struct futhark_context *ctx, struct futhark_opaque_sortInfo_long **out0, const int64_t in0, const int16_t in1, const struct futhark_i64_1d *in2);
int futhark_entry_radixSortColumn_short(struct futhark_context *ctx, struct futhark_opaque_sortInfo_short **out0, const int64_t in0, const int16_t in1, const struct futhark_i16_1d *in2);
int futhark_entry_radixSortRelation_double(struct futhark_context *ctx, struct futhark_opaque_sortStruct_double **out0, const int16_t in0, const struct futhark_opaque_sortStruct_double *in1);
int futhark_entry_radixSortRelation_float(struct futhark_context *ctx, struct futhark_opaque_sortStruct_float **out0, const int16_t in0, const struct futhark_opaque_sortStruct_float *in1);
int futhark_entry_radixSortRelation_int(struct futhark_context *ctx, struct futhark_opaque_sortStruct_int **out0, const int16_t in0, const struct futhark_opaque_sortStruct_int *in1);
int futhark_entry_radixSortRelation_long(struct futhark_context *ctx, struct futhark_opaque_sortStruct_long **out0, const int16_t in0, const struct futhark_opaque_sortStruct_long *in1);
int futhark_entry_radixSortRelation_short(struct futhark_context *ctx, struct futhark_opaque_sortStruct_short **out0, const int16_t in0, const struct futhark_opaque_sortStruct_short *in1);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_c
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
