// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs).
// git: 1de4f0c (Fri Jan 24 11:10:52 2025 +0100)
// Compiled with GHC 9.4.8.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_f32_1d;
struct futhark_f32_1d *futhark_new_f32_1d(struct futhark_context *ctx, const float *data, int64_t dim0);
struct futhark_f32_1d *futhark_new_raw_f32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
int futhark_values_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr, float *data);
int futhark_index_f32_1d(struct futhark_context *ctx, float *out, struct futhark_f32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
const int64_t *futhark_shape_f32_1d(struct futhark_context *ctx, struct futhark_f32_1d *arr);
struct futhark_f64_1d;
struct futhark_f64_1d *futhark_new_f64_1d(struct futhark_context *ctx, const double *data, int64_t dim0);
struct futhark_f64_1d *futhark_new_raw_f64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
int futhark_values_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr, double *data);
int futhark_index_f64_1d(struct futhark_context *ctx, double *out, struct futhark_f64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
const int64_t *futhark_shape_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
struct futhark_i16_1d;
struct futhark_i16_1d *futhark_new_i16_1d(struct futhark_context *ctx, const int16_t *data, int64_t dim0);
struct futhark_i16_1d *futhark_new_raw_i16_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr);
int futhark_values_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr, int16_t *data);
int futhark_index_i16_1d(struct futhark_context *ctx, int16_t *out, struct futhark_i16_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr);
const int64_t *futhark_shape_i16_1d(struct futhark_context *ctx, struct futhark_i16_1d *arr);
struct futhark_i32_1d;
struct futhark_i32_1d *futhark_new_i32_1d(struct futhark_context *ctx, const int32_t *data, int64_t dim0);
struct futhark_i32_1d *futhark_new_raw_i32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
int futhark_values_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr, int32_t *data);
int futhark_index_i32_1d(struct futhark_context *ctx, int32_t *out, struct futhark_i32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
const int64_t *futhark_shape_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
struct futhark_i64_1d;
struct futhark_i64_1d *futhark_new_i64_1d(struct futhark_context *ctx, const int64_t *data, int64_t dim0);
struct futhark_i64_1d *futhark_new_raw_i64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
int futhark_values_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr, int64_t *data);
int futhark_index_i64_1d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
const int64_t *futhark_shape_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);

// Opaque values
struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92;
struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f;
struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff;
struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1;
struct futhark_opaque_2974d0f3047e9d3501564828343f2c13;
int futhark_free_opaque_f13eaec8a3376b0779b01fe677f16c92(struct futhark_context *ctx, struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92 *obj);
int futhark_store_opaque_f13eaec8a3376b0779b01fe677f16c92(struct futhark_context *ctx, const struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92 *obj, void **p, size_t *n);
struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92 *futhark_restore_opaque_f13eaec8a3376b0779b01fe677f16c92(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_f13eaec8a3376b0779b01fe677f16c92_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92 *obj);
int futhark_project_opaque_f13eaec8a3376b0779b01fe677f16c92_xs(struct futhark_context *ctx, struct futhark_f32_1d **out, const struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92 *obj);
int futhark_new_opaque_f13eaec8a3376b0779b01fe677f16c92(struct futhark_context *ctx, struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92 **out, const struct futhark_i64_1d *f_is, const struct futhark_f32_1d *f_xs);
int futhark_free_opaque_aba46ca62dc1438ebfcef511b514a77f(struct futhark_context *ctx, struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f *obj);
int futhark_store_opaque_aba46ca62dc1438ebfcef511b514a77f(struct futhark_context *ctx, const struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f *obj, void **p, size_t *n);
struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f *futhark_restore_opaque_aba46ca62dc1438ebfcef511b514a77f(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_aba46ca62dc1438ebfcef511b514a77f_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f *obj);
int futhark_project_opaque_aba46ca62dc1438ebfcef511b514a77f_xs(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f *obj);
int futhark_new_opaque_aba46ca62dc1438ebfcef511b514a77f(struct futhark_context *ctx, struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f **out, const struct futhark_i64_1d *f_is, const struct futhark_f64_1d *f_xs);
int futhark_free_opaque_92a35df953f5fcb88a414672f1c163ff(struct futhark_context *ctx, struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff *obj);
int futhark_store_opaque_92a35df953f5fcb88a414672f1c163ff(struct futhark_context *ctx, const struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff *obj, void **p, size_t *n);
struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff *futhark_restore_opaque_92a35df953f5fcb88a414672f1c163ff(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_92a35df953f5fcb88a414672f1c163ff_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff *obj);
int futhark_project_opaque_92a35df953f5fcb88a414672f1c163ff_xs(struct futhark_context *ctx, struct futhark_i16_1d **out, const struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff *obj);
int futhark_new_opaque_92a35df953f5fcb88a414672f1c163ff(struct futhark_context *ctx, struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff **out, const struct futhark_i64_1d *f_is, const struct futhark_i16_1d *f_xs);
int futhark_free_opaque_e39e4750ffc51fc6df472c4e100ea5b1(struct futhark_context *ctx, struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1 *obj);
int futhark_store_opaque_e39e4750ffc51fc6df472c4e100ea5b1(struct futhark_context *ctx, const struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1 *obj, void **p, size_t *n);
struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1 *futhark_restore_opaque_e39e4750ffc51fc6df472c4e100ea5b1(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_e39e4750ffc51fc6df472c4e100ea5b1_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1 *obj);
int futhark_project_opaque_e39e4750ffc51fc6df472c4e100ea5b1_xs(struct futhark_context *ctx, struct futhark_i32_1d **out, const struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1 *obj);
int futhark_new_opaque_e39e4750ffc51fc6df472c4e100ea5b1(struct futhark_context *ctx, struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1 **out, const struct futhark_i64_1d *f_is, const struct futhark_i32_1d *f_xs);
int futhark_free_opaque_2974d0f3047e9d3501564828343f2c13(struct futhark_context *ctx, struct futhark_opaque_2974d0f3047e9d3501564828343f2c13 *obj);
int futhark_store_opaque_2974d0f3047e9d3501564828343f2c13(struct futhark_context *ctx, const struct futhark_opaque_2974d0f3047e9d3501564828343f2c13 *obj, void **p, size_t *n);
struct futhark_opaque_2974d0f3047e9d3501564828343f2c13 *futhark_restore_opaque_2974d0f3047e9d3501564828343f2c13(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_2974d0f3047e9d3501564828343f2c13_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_2974d0f3047e9d3501564828343f2c13 *obj);
int futhark_project_opaque_2974d0f3047e9d3501564828343f2c13_xs(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_2974d0f3047e9d3501564828343f2c13 *obj);
int futhark_new_opaque_2974d0f3047e9d3501564828343f2c13(struct futhark_context *ctx, struct futhark_opaque_2974d0f3047e9d3501564828343f2c13 **out, const struct futhark_i64_1d *f_is, const struct futhark_i64_1d *f_xs);

// Entry points
int futhark_entry_orderByIndices_double(struct futhark_context *ctx, struct futhark_f64_1d **out0, const struct futhark_i64_1d *in0, const struct futhark_f64_1d *in1);
int futhark_entry_orderByIndices_float(struct futhark_context *ctx, struct futhark_f32_1d **out0, const struct futhark_i64_1d *in0, const struct futhark_f32_1d *in1);
int futhark_entry_orderByIndices_int(struct futhark_context *ctx, struct futhark_i32_1d **out0, const struct futhark_i64_1d *in0, const struct futhark_i32_1d *in1);
int futhark_entry_orderByIndices_long(struct futhark_context *ctx, struct futhark_i64_1d **out0, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1);
int futhark_entry_orderByIndices_short(struct futhark_context *ctx, struct futhark_i16_1d **out0, const struct futhark_i64_1d *in0, const struct futhark_i16_1d *in1);
int futhark_entry_sortColumn_double(struct futhark_context *ctx, struct futhark_opaque_aba46ca62dc1438ebfcef511b514a77f **out0, const struct futhark_f64_1d *in0);
int futhark_entry_sortColumn_float(struct futhark_context *ctx, struct futhark_opaque_f13eaec8a3376b0779b01fe677f16c92 **out0, const struct futhark_f32_1d *in0);
int futhark_entry_sortColumn_int(struct futhark_context *ctx, struct futhark_opaque_e39e4750ffc51fc6df472c4e100ea5b1 **out0, const struct futhark_i32_1d *in0);
int futhark_entry_sortColumn_long(struct futhark_context *ctx, struct futhark_opaque_2974d0f3047e9d3501564828343f2c13 **out0, const struct futhark_i64_1d *in0);
int futhark_entry_sortColumn_short(struct futhark_context *ctx, struct futhark_opaque_92a35df953f5fcb88a414672f1c163ff **out0, const struct futhark_i16_1d *in0);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_c
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
