// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs).
// git: 1de4f0c (Fri Jan 24 11:10:52 2025 +0100)
// Compiled with GHC 9.4.8.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_bool_1d;
struct futhark_bool_1d *futhark_new_bool_1d(struct futhark_context *ctx, const bool *data, int64_t dim0);
struct futhark_bool_1d *futhark_new_raw_bool_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
int futhark_values_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr, bool *data);
int futhark_index_bool_1d(struct futhark_context *ctx, bool *out, struct futhark_bool_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
const int64_t *futhark_shape_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
struct futhark_f64_1d;
struct futhark_f64_1d *futhark_new_f64_1d(struct futhark_context *ctx, const double *data, int64_t dim0);
struct futhark_f64_1d *futhark_new_raw_f64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
int futhark_values_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr, double *data);
int futhark_index_f64_1d(struct futhark_context *ctx, double *out, struct futhark_f64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
const int64_t *futhark_shape_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
struct futhark_i64_1d;
struct futhark_i64_1d *futhark_new_i64_1d(struct futhark_context *ctx, const int64_t *data, int64_t dim0);
struct futhark_i64_1d *futhark_new_raw_i64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
int futhark_values_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr, int64_t *data);
int futhark_index_i64_1d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
const int64_t *futhark_shape_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);

// Opaque values
struct futhark_opaque_dbscan_result;
int futhark_free_opaque_dbscan_result(struct futhark_context *ctx, struct futhark_opaque_dbscan_result *obj);
int futhark_store_opaque_dbscan_result(struct futhark_context *ctx, const struct futhark_opaque_dbscan_result *obj, void **p, size_t *n);
struct futhark_opaque_dbscan_result *futhark_restore_opaque_dbscan_result(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_dbscan_result_cluster_id(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_dbscan_result *obj);
int futhark_project_opaque_dbscan_result_is_core(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_dbscan_result *obj);
int futhark_new_opaque_dbscan_result(struct futhark_context *ctx, struct futhark_opaque_dbscan_result **out, const struct futhark_i64_1d *f_cluster_id, const struct futhark_bool_1d *f_is_core);

// Entry points
int futhark_entry_crop_column_f64(struct futhark_context *ctx, struct futhark_f64_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_f64_1d *in2);
int futhark_entry_do_grid_dbscan_2d_f64(struct futhark_context *ctx, struct futhark_opaque_dbscan_result **out0, const int64_t in0, const int64_t in1, const double in2, const int64_t in3, const struct futhark_f64_1d *in4, const struct futhark_f64_1d *in5);
int futhark_entry_do_grid_dbscan_3d_f64(struct futhark_context *ctx, struct futhark_opaque_dbscan_result **out0, const int64_t in0, const int64_t in1, const double in2, const int64_t in3, const struct futhark_f64_1d *in4, const struct futhark_f64_1d *in5, const struct futhark_f64_1d *in6);
int futhark_entry_do_kd_dbscan_2d_f64(struct futhark_context *ctx, struct futhark_opaque_dbscan_result **out0, const int64_t in0, const int64_t in1, const double in2, const int64_t in3, const struct futhark_f64_1d *in4, const struct futhark_f64_1d *in5);
int futhark_entry_do_kd_dbscan_3d_f64(struct futhark_context *ctx, struct futhark_opaque_dbscan_result **out0, const int64_t in0, const int64_t in1, const double in2, const int64_t in3, const struct futhark_f64_1d *in4, const struct futhark_f64_1d *in5, const struct futhark_f64_1d *in6);
int futhark_entry_init_column_f64(struct futhark_context *ctx, struct futhark_f64_1d **out0, const int64_t in0);
int futhark_entry_write_column_f64(struct futhark_context *ctx, struct futhark_f64_1d **out0, const int64_t in0, const struct futhark_f64_1d *in1, const struct futhark_f64_1d *in2);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_c
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
