// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs).
// git: 1de4f0c (Fri Jan 24 11:10:52 2025 +0100)
// Compiled with GHC 9.4.8.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_bool_1d;
struct futhark_bool_1d *futhark_new_bool_1d(struct futhark_context *ctx, const bool *data, int64_t dim0);
struct futhark_bool_1d *futhark_new_raw_bool_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
int futhark_values_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr, bool *data);
int futhark_index_bool_1d(struct futhark_context *ctx, bool *out, struct futhark_bool_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
const int64_t *futhark_shape_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
struct futhark_f64_1d;
struct futhark_f64_1d *futhark_new_f64_1d(struct futhark_context *ctx, const double *data, int64_t dim0);
struct futhark_f64_1d *futhark_new_raw_f64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
int futhark_values_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr, double *data);
int futhark_index_f64_1d(struct futhark_context *ctx, double *out, struct futhark_f64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
const int64_t *futhark_shape_f64_1d(struct futhark_context *ctx, struct futhark_f64_1d *arr);
struct futhark_i64_1d;
struct futhark_i64_1d *futhark_new_i64_1d(struct futhark_context *ctx, const int64_t *data, int64_t dim0);
struct futhark_i64_1d *futhark_new_raw_i64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
int futhark_values_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr, int64_t *data);
int futhark_index_i64_1d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
const int64_t *futhark_shape_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);

// Opaque values
struct futhark_opaque_00764e1f7379f14f22282d21712a8514;
struct futhark_opaque_5797e930517e531e6d939a24b1db07bd;
struct futhark_opaque_tup2_f64_f64;
struct futhark_opaque_tup2_i64_i64;
struct futhark_opaque_arr1d_tup2_f64_f64;
struct futhark_opaque_arr1d_tup2_i64_i64;
struct futhark_opaque_collisionTable;
struct futhark_opaque_dbcHandler_double;
struct futhark_opaque_flushedData_double;
struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb;
struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763;
struct futhark_opaque_2f462154888958ab775ddc32a175f568;
int futhark_free_opaque_00764e1f7379f14f22282d21712a8514(struct futhark_context *ctx, struct futhark_opaque_00764e1f7379f14f22282d21712a8514 *obj);
int futhark_store_opaque_00764e1f7379f14f22282d21712a8514(struct futhark_context *ctx, const struct futhark_opaque_00764e1f7379f14f22282d21712a8514 *obj, void **p, size_t *n);
struct futhark_opaque_00764e1f7379f14f22282d21712a8514 *futhark_restore_opaque_00764e1f7379f14f22282d21712a8514(struct futhark_context *ctx, const void *p);
int futhark_new_opaque_00764e1f7379f14f22282d21712a8514_degrees(struct futhark_context *ctx, struct futhark_opaque_00764e1f7379f14f22282d21712a8514 **out);
int futhark_destruct_opaque_00764e1f7379f14f22282d21712a8514_degrees(struct futhark_context *ctx, const struct futhark_opaque_00764e1f7379f14f22282d21712a8514 *obj);
int futhark_new_opaque_00764e1f7379f14f22282d21712a8514_radians(struct futhark_context *ctx, struct futhark_opaque_00764e1f7379f14f22282d21712a8514 **out);
int futhark_destruct_opaque_00764e1f7379f14f22282d21712a8514_radians(struct futhark_context *ctx, const struct futhark_opaque_00764e1f7379f14f22282d21712a8514 *obj);
int futhark_variant_opaque_00764e1f7379f14f22282d21712a8514(struct futhark_context *ctx, const struct futhark_opaque_00764e1f7379f14f22282d21712a8514 *v);
int futhark_free_opaque_5797e930517e531e6d939a24b1db07bd(struct futhark_context *ctx, struct futhark_opaque_5797e930517e531e6d939a24b1db07bd *obj);
int futhark_store_opaque_5797e930517e531e6d939a24b1db07bd(struct futhark_context *ctx, const struct futhark_opaque_5797e930517e531e6d939a24b1db07bd *obj, void **p, size_t *n);
struct futhark_opaque_5797e930517e531e6d939a24b1db07bd *futhark_restore_opaque_5797e930517e531e6d939a24b1db07bd(struct futhark_context *ctx, const void *p);
int futhark_new_opaque_5797e930517e531e6d939a24b1db07bd_euclidean(struct futhark_context *ctx, struct futhark_opaque_5797e930517e531e6d939a24b1db07bd **out);
int futhark_destruct_opaque_5797e930517e531e6d939a24b1db07bd_euclidean(struct futhark_context *ctx, const struct futhark_opaque_5797e930517e531e6d939a24b1db07bd *obj);
int futhark_new_opaque_5797e930517e531e6d939a24b1db07bd_haversine(struct futhark_context *ctx, struct futhark_opaque_5797e930517e531e6d939a24b1db07bd **out);
int futhark_destruct_opaque_5797e930517e531e6d939a24b1db07bd_haversine(struct futhark_context *ctx, const struct futhark_opaque_5797e930517e531e6d939a24b1db07bd *obj);
int futhark_variant_opaque_5797e930517e531e6d939a24b1db07bd(struct futhark_context *ctx, const struct futhark_opaque_5797e930517e531e6d939a24b1db07bd *v);
int futhark_free_opaque_tup2_f64_f64(struct futhark_context *ctx, struct futhark_opaque_tup2_f64_f64 *obj);
int futhark_store_opaque_tup2_f64_f64(struct futhark_context *ctx, const struct futhark_opaque_tup2_f64_f64 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_f64_f64 *futhark_restore_opaque_tup2_f64_f64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_f64_f64_0(struct futhark_context *ctx, double *out, const struct futhark_opaque_tup2_f64_f64 *obj);
int futhark_project_opaque_tup2_f64_f64_1(struct futhark_context *ctx, double *out, const struct futhark_opaque_tup2_f64_f64 *obj);
int futhark_new_opaque_tup2_f64_f64(struct futhark_context *ctx, struct futhark_opaque_tup2_f64_f64 **out, const double f_0, const double f_1);
int futhark_free_opaque_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_i64 *obj);
int futhark_store_opaque_tup2_i64_i64(struct futhark_context *ctx, const struct futhark_opaque_tup2_i64_i64 *obj, void **p, size_t *n);
struct futhark_opaque_tup2_i64_i64 *futhark_restore_opaque_tup2_i64_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tup2_i64_i64_0(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tup2_i64_i64 *obj);
int futhark_project_opaque_tup2_i64_i64_1(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tup2_i64_i64 *obj);
int futhark_new_opaque_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_i64 **out, const int64_t f_0, const int64_t f_1);
int futhark_free_opaque_arr1d_tup2_f64_f64(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_f64_f64 *obj);
int futhark_store_opaque_arr1d_tup2_f64_f64(struct futhark_context *ctx, const struct futhark_opaque_arr1d_tup2_f64_f64 *obj, void **p, size_t *n);
struct futhark_opaque_arr1d_tup2_f64_f64 *futhark_restore_opaque_arr1d_tup2_f64_f64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_arr1d_tup2_f64_f64_0(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_arr1d_tup2_f64_f64 *obj);
int futhark_project_opaque_arr1d_tup2_f64_f64_1(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_arr1d_tup2_f64_f64 *obj);
int futhark_zip_opaque_arr1d_tup2_f64_f64(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_f64_f64 **out, const struct futhark_f64_1d *f_0, const struct futhark_f64_1d *f_1);
int futhark_index_opaque_arr1d_tup2_f64_f64(struct futhark_context *ctx, struct futhark_opaque_tup2_f64_f64 **out, struct futhark_opaque_arr1d_tup2_f64_f64 *arr, int64_t i0);
const int64_t *futhark_shape_opaque_arr1d_tup2_f64_f64(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_f64_f64 *arr);
int futhark_free_opaque_arr1d_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_i64_i64 *obj);
int futhark_store_opaque_arr1d_tup2_i64_i64(struct futhark_context *ctx, const struct futhark_opaque_arr1d_tup2_i64_i64 *obj, void **p, size_t *n);
struct futhark_opaque_arr1d_tup2_i64_i64 *futhark_restore_opaque_arr1d_tup2_i64_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_arr1d_tup2_i64_i64_0(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_arr1d_tup2_i64_i64 *obj);
int futhark_project_opaque_arr1d_tup2_i64_i64_1(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_arr1d_tup2_i64_i64 *obj);
int futhark_zip_opaque_arr1d_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_i64_i64 **out, const struct futhark_i64_1d *f_0, const struct futhark_i64_1d *f_1);
int futhark_index_opaque_arr1d_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_tup2_i64_i64 **out, struct futhark_opaque_arr1d_tup2_i64_i64 *arr, int64_t i0);
const int64_t *futhark_shape_opaque_arr1d_tup2_i64_i64(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_i64_i64 *arr);
int futhark_free_opaque_collisionTable(struct futhark_context *ctx, struct futhark_opaque_collisionTable *obj);
int futhark_store_opaque_collisionTable(struct futhark_context *ctx, const struct futhark_opaque_collisionTable *obj, void **p, size_t *n);
struct futhark_opaque_collisionTable *futhark_restore_opaque_collisionTable(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_collisionTable_chain_id(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_collisionTable *obj);
int futhark_project_opaque_collisionTable_ncc(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_collisionTable *obj);
int futhark_project_opaque_collisionTable_replaceWith(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_collisionTable *obj);
int futhark_new_opaque_collisionTable(struct futhark_context *ctx, struct futhark_opaque_collisionTable **out, const struct futhark_i64_1d *f_chain_id, const int64_t f_ncc, const struct futhark_i64_1d *f_replaceWith);
int futhark_free_opaque_dbcHandler_double(struct futhark_context *ctx, struct futhark_opaque_dbcHandler_double *obj);
int futhark_store_opaque_dbcHandler_double(struct futhark_context *ctx, const struct futhark_opaque_dbcHandler_double *obj, void **p, size_t *n);
struct futhark_opaque_dbcHandler_double *futhark_restore_opaque_dbcHandler_double(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_dbcHandler_double_chain_collisions(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_i64_i64 **out, const struct futhark_opaque_dbcHandler_double *obj);
int futhark_project_opaque_dbcHandler_double_clBase(struct futhark_context *ctx, struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb **out, const struct futhark_opaque_dbcHandler_double *obj);
int futhark_project_opaque_dbcHandler_double_clProc(struct futhark_context *ctx, struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 **out, const struct futhark_opaque_dbcHandler_double *obj);
int futhark_project_opaque_dbcHandler_double_current_partition(struct futhark_context *ctx, struct futhark_opaque_2f462154888958ab775ddc32a175f568 **out, const struct futhark_opaque_dbcHandler_double *obj);
int futhark_project_opaque_dbcHandler_double_toFlush_dat(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_f64_f64 **out, const struct futhark_opaque_dbcHandler_double *obj);
int futhark_project_opaque_dbcHandler_double_toFlush_ids(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_dbcHandler_double *obj);
int futhark_new_opaque_dbcHandler_double(struct futhark_context *ctx, struct futhark_opaque_dbcHandler_double **out, const struct futhark_opaque_arr1d_tup2_i64_i64 *f_chain_collisions, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *f_clBase, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *f_clProc, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *f_current_partition, const struct futhark_opaque_arr1d_tup2_f64_f64 *f_toFlush_dat, const struct futhark_i64_1d *f_toFlush_ids);
int futhark_free_opaque_flushedData_double(struct futhark_context *ctx, struct futhark_opaque_flushedData_double *obj);
int futhark_store_opaque_flushedData_double(struct futhark_context *ctx, const struct futhark_opaque_flushedData_double *obj, void **p, size_t *n);
struct futhark_opaque_flushedData_double *futhark_restore_opaque_flushedData_double(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_flushedData_double_chain_ids(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_flushedData_double *obj);
int futhark_project_opaque_flushedData_double_xs(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_flushedData_double *obj);
int futhark_project_opaque_flushedData_double_ys(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_flushedData_double *obj);
int futhark_new_opaque_flushedData_double(struct futhark_context *ctx, struct futhark_opaque_flushedData_double **out, const struct futhark_i64_1d *f_chain_ids, const struct futhark_f64_1d *f_xs, const struct futhark_f64_1d *f_ys);
int futhark_free_opaque_8b7e80c3fb80a9a7700efe8e89371deb(struct futhark_context *ctx, struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_store_opaque_8b7e80c3fb80a9a7700efe8e89371deb(struct futhark_context *ctx, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj, void **p, size_t *n);
struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *futhark_restore_opaque_8b7e80c3fb80a9a7700efe8e89371deb(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_angle_t(struct futhark_context *ctx, struct futhark_opaque_00764e1f7379f14f22282d21712a8514 **out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_dist_t(struct futhark_context *ctx, struct futhark_opaque_5797e930517e531e6d939a24b1db07bd **out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_eps(struct futhark_context *ctx, double *out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_m_size(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_maxs(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_minPts(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_mins(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_part_per_dim(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_radius(struct futhark_context *ctx, double *out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_step_per_dim(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_project_opaque_8b7e80c3fb80a9a7700efe8e89371deb_total_partitions(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb *obj);
int futhark_new_opaque_8b7e80c3fb80a9a7700efe8e89371deb(struct futhark_context *ctx, struct futhark_opaque_8b7e80c3fb80a9a7700efe8e89371deb **out, const struct futhark_opaque_00764e1f7379f14f22282d21712a8514 *f_angle_t, const struct futhark_opaque_5797e930517e531e6d939a24b1db07bd *f_dist_t, const double f_eps, const int64_t f_m_sizze, const struct futhark_f64_1d *f_maxs, const int64_t f_minPts, const struct futhark_f64_1d *f_mins, const struct futhark_i64_1d *f_part_per_dim, const double f_radius, const struct futhark_f64_1d *f_step_per_dim, const int64_t f_total_partitions);
int futhark_free_opaque_a8fdbed66266f52db9d5a0da8b1f6763(struct futhark_context *ctx, struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_store_opaque_a8fdbed66266f52db9d5a0da8b1f6763(struct futhark_context *ctx, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj, void **p, size_t *n);
struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *futhark_restore_opaque_a8fdbed66266f52db9d5a0da8b1f6763(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_buff_isCore(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_buffered_ids(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_buffered_pts(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_f64_f64 **out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_chainOffs(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_cur_part_id(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_cur_part_order(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_isPartVisited(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_next_offs(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_offs(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_project_opaque_a8fdbed66266f52db9d5a0da8b1f6763_relevantParts(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 *obj);
int futhark_new_opaque_a8fdbed66266f52db9d5a0da8b1f6763(struct futhark_context *ctx, struct futhark_opaque_a8fdbed66266f52db9d5a0da8b1f6763 **out, const struct futhark_bool_1d *f_buff_isCore, const struct futhark_i64_1d *f_buffered_ids, const struct futhark_opaque_arr1d_tup2_f64_f64 *f_buffered_pts, const int64_t f_chainOffs, const int64_t f_cur_part_id, const int64_t f_cur_part_order, const struct futhark_bool_1d *f_isPartVisited, const int64_t f_next_offs, const int64_t f_offs, const struct futhark_i64_1d *f_relevantParts);
int futhark_free_opaque_2f462154888958ab775ddc32a175f568(struct futhark_context *ctx, struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_store_opaque_2f462154888958ab775ddc32a175f568(struct futhark_context *ctx, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj, void **p, size_t *n);
struct futhark_opaque_2f462154888958ab775ddc32a175f568 *futhark_restore_opaque_2f462154888958ab775ddc32a175f568(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_chain_ids(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_dat(struct futhark_context *ctx, struct futhark_opaque_arr1d_tup2_f64_f64 **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_isCore(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_isMargin(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_isNeighbourVisited(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_isTightMargin(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_max_coord(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_min_coord(struct futhark_context *ctx, struct futhark_f64_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_neighbours(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_project_opaque_2f462154888958ab775ddc32a175f568_part_id(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_2f462154888958ab775ddc32a175f568 *obj);
int futhark_new_opaque_2f462154888958ab775ddc32a175f568(struct futhark_context *ctx, struct futhark_opaque_2f462154888958ab775ddc32a175f568 **out, const struct futhark_i64_1d *f_chain_ids, const struct futhark_opaque_arr1d_tup2_f64_f64 *f_dat, const struct futhark_bool_1d *f_isCore, const struct futhark_bool_1d *f_isMargin, const struct futhark_bool_1d *f_isNeighbourVisited, const struct futhark_bool_1d *f_isTightMargin, const struct futhark_f64_1d *f_max_coord, const struct futhark_f64_1d *f_min_coord, const struct futhark_i64_1d *f_neighbours, const int64_t f_part_id);

// Entry points
int futhark_entry_add_next_partition_double(struct futhark_context *ctx, struct futhark_opaque_dbcHandler_double **out0, const struct futhark_opaque_dbcHandler_double *in0, const int64_t in1, const struct futhark_f64_1d *in2, const struct futhark_f64_1d *in3);
int futhark_entry_do_DBSCAN_double(struct futhark_context *ctx, struct futhark_opaque_dbcHandler_double **out0, const struct futhark_opaque_dbcHandler_double *in0, const int64_t in1);
int futhark_entry_flush_dat_double(struct futhark_context *ctx, struct futhark_opaque_flushedData_double **out0, const struct futhark_opaque_dbcHandler_double *in0);
int futhark_entry_make_collisions_compact_double(struct futhark_context *ctx, struct futhark_opaque_collisionTable **out0, const struct futhark_opaque_dbcHandler_double *in0);
int futhark_entry_mk_dbcHandler_double(struct futhark_context *ctx, struct futhark_opaque_dbcHandler_double **out0, const double in0, const double in1, const double in2, const double in3, const int64_t in4, const int64_t in5, const bool in6, const bool in7, const double in8, const double in9, const int64_t in10, const int64_t in11);
int futhark_entry_next_partition_to_read_double(struct futhark_context *ctx, int64_t *out0, const struct futhark_opaque_dbcHandler_double *in0);
int futhark_entry_rectify_cluster_ids_double(struct futhark_context *ctx, struct futhark_i64_1d **out0, const struct futhark_i64_1d *in0, const struct futhark_opaque_collisionTable *in1, const int64_t in2);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_c
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
