// Generated by Futhark 0.26.0 (prerelease - include info below when reporting bugs).
// git: 1de4f0c (Fri Jan 24 11:10:52 2025 +0100)
// Compiled with GHC 9.4.8.
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_bool_1d;
struct futhark_bool_1d *futhark_new_bool_1d(struct futhark_context *ctx, const bool *data, int64_t dim0);
struct futhark_bool_1d *futhark_new_raw_bool_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
int futhark_values_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr, bool *data);
int futhark_index_bool_1d(struct futhark_context *ctx, bool *out, struct futhark_bool_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
const int64_t *futhark_shape_bool_1d(struct futhark_context *ctx, struct futhark_bool_1d *arr);
struct futhark_i32_1d;
struct futhark_i32_1d *futhark_new_i32_1d(struct futhark_context *ctx, const int32_t *data, int64_t dim0);
struct futhark_i32_1d *futhark_new_raw_i32_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
int futhark_values_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr, int32_t *data);
int futhark_index_i32_1d(struct futhark_context *ctx, int32_t *out, struct futhark_i32_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
const int64_t *futhark_shape_i32_1d(struct futhark_context *ctx, struct futhark_i32_1d *arr);
struct futhark_i32_2d;
struct futhark_i32_2d *futhark_new_i32_2d(struct futhark_context *ctx, const int32_t *data, int64_t dim0, int64_t dim1);
struct futhark_i32_2d *futhark_new_raw_i32_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_i32_2d(struct futhark_context *ctx, struct futhark_i32_2d *arr);
int futhark_values_i32_2d(struct futhark_context *ctx, struct futhark_i32_2d *arr, int32_t *data);
int futhark_index_i32_2d(struct futhark_context *ctx, int32_t *out, struct futhark_i32_2d *arr, int64_t i0, int64_t i1);
unsigned char *futhark_values_raw_i32_2d(struct futhark_context *ctx, struct futhark_i32_2d *arr);
const int64_t *futhark_shape_i32_2d(struct futhark_context *ctx, struct futhark_i32_2d *arr);
struct futhark_i64_1d;
struct futhark_i64_1d *futhark_new_i64_1d(struct futhark_context *ctx, const int64_t *data, int64_t dim0);
struct futhark_i64_1d *futhark_new_raw_i64_1d(struct futhark_context *ctx, unsigned char *data, int64_t dim0);
int futhark_free_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
int futhark_values_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr, int64_t *data);
int futhark_index_i64_1d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_1d *arr, int64_t i0);
unsigned char *futhark_values_raw_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
const int64_t *futhark_shape_i64_1d(struct futhark_context *ctx, struct futhark_i64_1d *arr);
struct futhark_i64_2d;
struct futhark_i64_2d *futhark_new_i64_2d(struct futhark_context *ctx, const int64_t *data, int64_t dim0, int64_t dim1);
struct futhark_i64_2d *futhark_new_raw_i64_2d(struct futhark_context *ctx, unsigned char *data, int64_t dim0, int64_t dim1);
int futhark_free_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr);
int futhark_values_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr, int64_t *data);
int futhark_index_i64_2d(struct futhark_context *ctx, int64_t *out, struct futhark_i64_2d *arr, int64_t i0, int64_t i1);
unsigned char *futhark_values_raw_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr);
const int64_t *futhark_shape_i64_2d(struct futhark_context *ctx, struct futhark_i64_2d *arr);

// Opaque values
struct futhark_opaque_joinPairs_i32;
struct futhark_opaque_joinPairs_i64;
struct futhark_opaque_sortInfo_i32;
struct futhark_opaque_sortInfo_i64;
struct futhark_opaque_tps_bufferInfo;
struct futhark_opaque_tps_bufferProc;
int futhark_free_opaque_joinPairs_i32(struct futhark_context *ctx, struct futhark_opaque_joinPairs_i32 *obj);
int futhark_store_opaque_joinPairs_i32(struct futhark_context *ctx, const struct futhark_opaque_joinPairs_i32 *obj, void **p, size_t *n);
struct futhark_opaque_joinPairs_i32 *futhark_restore_opaque_joinPairs_i32(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_joinPairs_i32_ix(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_joinPairs_i32 *obj);
int futhark_project_opaque_joinPairs_i32_iy(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_joinPairs_i32 *obj);
int futhark_project_opaque_joinPairs_i32_vs(struct futhark_context *ctx, struct futhark_i32_1d **out, const struct futhark_opaque_joinPairs_i32 *obj);
int futhark_new_opaque_joinPairs_i32(struct futhark_context *ctx, struct futhark_opaque_joinPairs_i32 **out, const struct futhark_i64_1d *f_ix, const struct futhark_i64_1d *f_iy, const struct futhark_i32_1d *f_vs);
int futhark_free_opaque_joinPairs_i64(struct futhark_context *ctx, struct futhark_opaque_joinPairs_i64 *obj);
int futhark_store_opaque_joinPairs_i64(struct futhark_context *ctx, const struct futhark_opaque_joinPairs_i64 *obj, void **p, size_t *n);
struct futhark_opaque_joinPairs_i64 *futhark_restore_opaque_joinPairs_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_joinPairs_i64_ix(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_joinPairs_i64 *obj);
int futhark_project_opaque_joinPairs_i64_iy(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_joinPairs_i64 *obj);
int futhark_project_opaque_joinPairs_i64_vs(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_joinPairs_i64 *obj);
int futhark_new_opaque_joinPairs_i64(struct futhark_context *ctx, struct futhark_opaque_joinPairs_i64 **out, const struct futhark_i64_1d *f_ix, const struct futhark_i64_1d *f_iy, const struct futhark_i64_1d *f_vs);
int futhark_free_opaque_sortInfo_i32(struct futhark_context *ctx, struct futhark_opaque_sortInfo_i32 *obj);
int futhark_store_opaque_sortInfo_i32(struct futhark_context *ctx, const struct futhark_opaque_sortInfo_i32 *obj, void **p, size_t *n);
struct futhark_opaque_sortInfo_i32 *futhark_restore_opaque_sortInfo_i32(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortInfo_i32_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_i32 *obj);
int futhark_project_opaque_sortInfo_i32_ks(struct futhark_context *ctx, struct futhark_i32_1d **out, const struct futhark_opaque_sortInfo_i32 *obj);
int futhark_new_opaque_sortInfo_i32(struct futhark_context *ctx, struct futhark_opaque_sortInfo_i32 **out, const struct futhark_i64_1d *f_is, const struct futhark_i32_1d *f_ks);
int futhark_free_opaque_sortInfo_i64(struct futhark_context *ctx, struct futhark_opaque_sortInfo_i64 *obj);
int futhark_store_opaque_sortInfo_i64(struct futhark_context *ctx, const struct futhark_opaque_sortInfo_i64 *obj, void **p, size_t *n);
struct futhark_opaque_sortInfo_i64 *futhark_restore_opaque_sortInfo_i64(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_sortInfo_i64_is(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_i64 *obj);
int futhark_project_opaque_sortInfo_i64_ks(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_sortInfo_i64 *obj);
int futhark_new_opaque_sortInfo_i64(struct futhark_context *ctx, struct futhark_opaque_sortInfo_i64 **out, const struct futhark_i64_1d *f_is, const struct futhark_i64_1d *f_ks);
int futhark_free_opaque_tps_bufferInfo(struct futhark_context *ctx, struct futhark_opaque_tps_bufferInfo *obj);
int futhark_store_opaque_tps_bufferInfo(struct futhark_context *ctx, const struct futhark_opaque_tps_bufferInfo *obj, void **p, size_t *n);
struct futhark_opaque_tps_bufferInfo *futhark_restore_opaque_tps_bufferInfo(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tps_bufferInfo_chunkSize(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tps_bufferInfo *obj);
int futhark_project_opaque_tps_bufferInfo_chunks_No(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tps_bufferInfo *obj);
int futhark_project_opaque_tps_bufferInfo_srcs_No(struct futhark_context *ctx, int64_t *out, const struct futhark_opaque_tps_bufferInfo *obj);
int futhark_new_opaque_tps_bufferInfo(struct futhark_context *ctx, struct futhark_opaque_tps_bufferInfo **out, const int64_t f_chunkSizze, const int64_t f_chunks_No, const int64_t f_srcs_No);
int futhark_free_opaque_tps_bufferProc(struct futhark_context *ctx, struct futhark_opaque_tps_bufferProc *obj);
int futhark_store_opaque_tps_bufferProc(struct futhark_context *ctx, const struct futhark_opaque_tps_bufferProc *obj, void **p, size_t *n);
struct futhark_opaque_tps_bufferProc *futhark_restore_opaque_tps_bufferProc(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_tps_bufferProc_freePos_waiting(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_tps_bufferProc *obj);
int futhark_project_opaque_tps_bufferProc_free_positions(struct futhark_context *ctx, struct futhark_i64_1d **out, const struct futhark_opaque_tps_bufferProc *obj);
int futhark_project_opaque_tps_bufferProc_isChunkTaken(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_tps_bufferProc *obj);
int futhark_project_opaque_tps_bufferProc_isSrcExhausted(struct futhark_context *ctx, struct futhark_bool_1d **out, const struct futhark_opaque_tps_bufferProc *obj);
int futhark_new_opaque_tps_bufferProc(struct futhark_context *ctx, struct futhark_opaque_tps_bufferProc **out, const struct futhark_i64_1d *f_freePos_waiting, const struct futhark_i64_1d *f_free_positions, const struct futhark_bool_1d *f_isChunkTaken, const struct futhark_bool_1d *f_isSrcExhausted);

// Entry points
int futhark_entry_afterFetching_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const struct futhark_opaque_tps_bufferInfo *in0, const struct futhark_opaque_tps_bufferProc *in1, const struct futhark_i32_1d *in2);
int futhark_entry_afterFetching_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const struct futhark_opaque_tps_bufferInfo *in0, const struct futhark_opaque_tps_bufferProc *in1, const struct futhark_i64_1d *in2);
int futhark_entry_crop_col_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i32_1d *in2);
int futhark_entry_crop_col_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_1d *in2);
int futhark_entry_fetchSorted_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const struct futhark_opaque_tps_bufferInfo *in0, const struct futhark_opaque_tps_bufferProc *in1, const struct futhark_i32_1d *in2);
int futhark_entry_fetchSorted_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const struct futhark_opaque_tps_bufferInfo *in0, const struct futhark_opaque_tps_bufferProc *in1, const struct futhark_i64_1d *in2);
int futhark_entry_fetchSorted_proc(struct futhark_context *ctx, struct futhark_opaque_tps_bufferProc **out0, const struct futhark_opaque_tps_bufferInfo *in0, const struct futhark_opaque_tps_bufferProc *in1);
int futhark_entry_gather_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const struct futhark_i32_1d *in0, const struct futhark_i64_1d *in1);
int futhark_entry_gather_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1);
int futhark_entry_init_bufferInfo(struct futhark_context *ctx, struct futhark_opaque_tps_bufferInfo **out0, const int64_t in0, const int64_t in1, const int64_t in2);
int futhark_entry_init_bufferProc(struct futhark_context *ctx, struct futhark_opaque_tps_bufferProc **out0, const struct futhark_opaque_tps_bufferInfo *in0);
int futhark_entry_init_tps_buffer_i32(struct futhark_context *ctx, struct futhark_i32_2d **out0, const struct futhark_opaque_tps_bufferInfo *in0);
int futhark_entry_init_tps_buffer_i64(struct futhark_context *ctx, struct futhark_i64_2d **out0, const struct futhark_opaque_tps_bufferInfo *in0);
int futhark_entry_innerSMJ_i32(struct futhark_context *ctx, struct futhark_opaque_joinPairs_i32 **out0, const struct futhark_i32_1d *in0, const struct futhark_i32_1d *in1);
int futhark_entry_innerSMJ_i64(struct futhark_context *ctx, struct futhark_opaque_joinPairs_i64 **out0, const struct futhark_i64_1d *in0, const struct futhark_i64_1d *in1);
int futhark_entry_markSrcExhausted_proc(struct futhark_context *ctx, struct futhark_opaque_tps_bufferProc **out0, const int64_t in0, const struct futhark_opaque_tps_bufferProc *in1);
int futhark_entry_mk_col_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const int64_t in0);
int futhark_entry_mk_col_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const int64_t in0);
int futhark_entry_next_unusedChunk_proc(struct futhark_context *ctx, int64_t *out0, const struct futhark_opaque_tps_bufferProc *in0);
int futhark_entry_radix_sort_i32_GFUR(struct futhark_context *ctx, struct futhark_opaque_sortInfo_i32 **out0, const struct futhark_i32_1d *in0);
int futhark_entry_radix_sort_i64_GFUR(struct futhark_context *ctx, struct futhark_opaque_sortInfo_i64 **out0, const struct futhark_i64_1d *in0);
int futhark_entry_read_col_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i32_1d *in2);
int futhark_entry_read_col_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_1d *in2);
int futhark_entry_tps_next_waiting_i32(struct futhark_context *ctx, int64_t *out0, const struct futhark_opaque_tps_bufferProc *in0, const struct futhark_i32_2d *in1);
int futhark_entry_tps_next_waiting_i64(struct futhark_context *ctx, int64_t *out0, const struct futhark_opaque_tps_bufferProc *in0, const struct futhark_i64_2d *in1);
int futhark_entry_update_col_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const int64_t in0, const struct futhark_i32_1d *in1, const struct futhark_i32_1d *in2);
int futhark_entry_update_col_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const int64_t in0, const struct futhark_i64_1d *in1, const struct futhark_i64_1d *in2);
int futhark_entry_writeToBuffer_i32(struct futhark_context *ctx, struct futhark_i32_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i32_2d *in2, const struct futhark_i32_1d *in3);
int futhark_entry_writeToBuffer_i64(struct futhark_context *ctx, struct futhark_i64_1d **out0, const int64_t in0, const int64_t in1, const struct futhark_i64_2d *in2, const struct futhark_i64_1d *in3);
int futhark_entry_writeToBuffer_proc(struct futhark_context *ctx, struct futhark_opaque_tps_bufferProc **out0, const int64_t in0, const int64_t in1, const struct futhark_opaque_tps_bufferProc *in2);
int futhark_entry_writeToWaiting_i32(struct futhark_context *ctx, struct futhark_i32_2d **out0, const int64_t in0, const struct futhark_i32_1d *in1, const struct futhark_i32_2d *in2);
int futhark_entry_writeToWaiting_i64(struct futhark_context *ctx, struct futhark_i64_2d **out0, const int64_t in0, const struct futhark_i64_1d *in1, const struct futhark_i64_2d *in2);
int futhark_entry_writeToWaiting_proc(struct futhark_context *ctx, struct futhark_opaque_tps_bufferProc **out0, const int64_t in0, const int64_t in1, const struct futhark_opaque_tps_bufferInfo *in2, const struct futhark_opaque_tps_bufferProc *in3);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
char *futhark_context_report(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_c
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
